### ISSUE TITLE
Unable to load on Fedora 29

### ISSUE THREAD

**Issue by mdl054** [corrad1nho/qomui#44]
OpenSuse Build Service lists 27 and 28. Unable to load on Fedora 29, rpm for 28 installs but will not run. Adding the repo installs it properly as well. I believe it may be a python problem. I can provide logs if necessary.

**Comment by corrad1nho** [comment]
Fedora 29 will be officially supported in the next release. Your suspicion that this is a Python problem is correct: The reason why it is not working is the update from Python3.6 to Python3.7.

**Comment by mdl054** [comment]
Thank you so much for looking into it and for all the hard work on Qomui, it's become an integral part of my workflow.

**Comment by corrad1nho** [comment]
I just published a package for Fedora Rawhide that sets the correct paths for Python 3.7.

**Comment by mdl054** [comment]
Thanks for publishing the update but unfortunately I still can't get it to run. I've spend a few days going through and triple checking but still no dice. I also tried the testing release from the build service as well.

**Comment by mdl054** [comment]
Absolutely. 
`~> qomui-service
Traceback (most recent call last):
  File "/usr/bin/qomui-service", line 11, in <module>
    load_entry_point('qomui==0.7.4', 'console_scripts', 'qomui-service')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/qomui/qomui_service.py", line 19, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
exit 1
``

and

`~> qomui-gui    
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 11, in <module>
    load_entry_point('qomui==0.7.4', 'gui_scripts', 'qomui-gui')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/qomui/qomui_gui.py", line 15, in <module>
    from PyQt5 import QtCore, QtWidgets, QtGui
ModuleNotFoundError: No module named 'PyQt5.sip'
exit 1
``

**Comment by corrad1nho** [comment]
Interesting. Can you try installing the following packages via dnf: python3-qt5 & python3-qt5-devel

**Comment by mdl054** [comment]
Sure.

`~> sudo dnf install python3-qt5
Package python3-qt5-5.11.2-4.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
~> sudo dnf install python3-qt5-devel
Last metadata expiration check: 0:00:14 ago on Thu 06 Dec 2018 08:13:33 AM EST.
Package python3-qt5-devel-5.11.2-4.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
`

**Comment by corrad1nho** [comment]
Sorry, python3-qt5-sip, too.

**Comment by mdl054** [comment]
`~> sudo dnf install python3-qt5-sip
Last metadata expiration check: 0:00:06 ago on Thu 06 Dec 2018 08:36:36 AM EST.
No match for argument: python3-qt5-sip
Error: Unable to find a match
`

**Comment by corrad1nho** [comment]
Strange, it's listed in the official repos: https://apps.fedoraproject.org/packages/python3-pyqt5-sip

**Comment by mdl054** [comment]
Not sure what happened exactly, however I ran the command again this evening and got a different result. I don't see how but it's possible I made a typo somewhere.

`~> sudo dnf install python3-pyqt5-sip
Last metadata expiration check: 14:19:58 ago on Thu 06 Dec 2018 08:36:36 AM EST.
Package python3-pyqt5-sip-4.19.12-9.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
~> 
`
